# Generated by Django 5.1.5 on 2025-02-06 15:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('age_range', models.CharField(blank=True, choices=[('14-17', '14-17'), ('18-24', '18-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-44', '40-44'), ('45-49', '45-49'), ('>50', '>50')], max_length=5, null=True)),
                ('full_name', models.TextField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 2, 6))])),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('country', models.TextField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
